language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
  - php: 5.6
    env: COMPOSER_FLAGS="--prefer-lowest"
  - php: 7.0
    env: COMPOSER_FLAGS="--prefer-lowest"
  - php: 7.1
    env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpspec run -v
  - vendor/bin/phpunit --coverage-text
